version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=/app/app.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port 80